{% set name = "shapeandshare.tiland" %}
{% set version = "0.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  entry_points:
    - tiland = shapeandshare.tiland.main:main

requirements:
  host:
    - pip
    - python>=3.12
    - setuptools
  run:
    - python>=3.12
    - fastapi
    - pydantic
    - uvicorn
    - joshburt/label/dev::shapeandshare.darkness

    # Project Maintenance and Documentation
#    - defaults:anaconda-project
#    - defaults:pylint
#    - defaults:black
#    - defaults:isort

    - pip
    - pip:
        - pygame


about:
  summary: "TiLand"
  license: MIT
  license_file: LICENSE
