# This is a basic workflow to help you get started with Actions

name: Pull Request

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the master branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

permissions:
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        channels: defaults,conda-forge,joshburt
        auto-activate-base: false
        activate-environment: ci.build
        environment-file: environment.github.yml
    - name: Conda Info
      run: |
        conda info
    - name: Run Auditing
      run: |
        anaconda-project run lint
    - name: Conda Build
      run: |
        make clean
        make setup
        make conda
#    - name: SonarCloud Scan
#      uses: sonarsource/sonarcloud-github-action@v2.3.0 # Ex: v2.1.0, See the latest version at https://github.com/marketplace/actions/sonarcloud-scan
#      env:
#        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Publish Dev Package
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      run: |
        anaconda --verbose --token $ANACONDA_TOKEN upload --user joshburt --label dev build/noarch/shapeandshare.tiland-*.tar.bz2 --force
